version: '3.7'

services:

  drillphish:
    build: .
    container_name: 'drillphish'
    hostname: 'drillphishhost'
    env_file:
      - '.env'
    ports:
      - '9000:8080/tcp'
      # - '4443:443/tcp'
    volumes:
      # Uncomment this for MacOS or Linux
      - "$PWD/source/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "$PWD/test/phishbook.html:/usr/share/nginx/html/index.html:ro"
      # Uncomment this for Windows
      # - "./source/nginx.conf:/etc/nginx/nginx.conf:ro"
      # - "./test/phishbook.html:/usr/share/nginx/html/index.html:ro"